name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: checkout config
        uses: actions/checkout@v3
        with:
          repository: lekkodev/example
          token: ${{ secrets.LEKKO_CI_GITHUB_PAT }}
          path: ci-example
      - name: run sidecar
        run: |
          cargo build
          cargo run -- --repo-path=$GITHUB_WORKSPACE/ci-example --mode=static > sidecar-out.log 2>&1 &
      - uses: bufbuild/buf-setup-action@v1
        with:
          buf_user: ${{ secrets.BUF_USER }}
          buf_api_token: ${{ secrets.BUF_API_TOKEN }}
          github_token: ${{ secrets.LEKKO_CI_GITHUB_PAT }}
      - name: read cargo logs
        run: |
          sleep 3
          cat sidecar-out.log
      - name: query sidecar
        run: |
          buf curl --data '{"namespace": "default", "key": "hello", "repoKey": {"ownerName": "lekkodev", "repoName": "example"}}' --protocol grpc --http2-prior-knowledge --schema buf.build/lekkodev/sdk http://localhost:50051/lekko.client.v1beta1.ConfigurationService/GetStringValue
      - name: ci
        run: make
