name: docker
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: checkout lekkodev/example
        uses: actions/checkout@v3
        with:
          repository: lekkodev/example
          token: ${{ secrets.LEKKO_CI_GITHUB_PAT }}
          path: lekkodev/example
      - name: check that config exists
        run: |
          ls -lash $GITHUB_WORKSPACE/lekkodev/example
      - name: Run sidecar
        run: |
          docker run --name sidecar -d -p 50051:50051 -v $GITHUB_WORKSPACE/lekkodev/example:/root/lekkodev/example public.ecr.aws/g0r8j2n2/lekko/sidecar:v0.0.13 --repo-path=/root/lekkodev/example --mode=static
      - uses: bufbuild/buf-setup-action@v1
        with:
          buf_user: ${{ secrets.BUF_USER }}
          buf_api_token: ${{ secrets.BUF_API_TOKEN }}
          github_token: ${{ secrets.LEKKO_CI_GITHUB_PAT }}
      - name: read docker logs
        run: |
          sleep 3
          docker logs sidecar
      - name: query sidecar
        run: |
          buf curl --data '{"namespace": "default", "key": "hello", "repoKey": {"ownerName": "lekkodev", "repoName": "example"}}' --protocol grpc --http2-prior-knowledge --schema buf.build/lekkodev/sdk http://localhost:50051/lekko.client.v1beta1.ConfigurationService/GetStringValue
