name: docker-integration
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: checkout lekkodev/integration-test
        uses: actions/checkout@v3
        with:
          repository: lekkodev/integration-test
          token: ${{ secrets.LEKKO_CI_GITHUB_PAT }}
          path: lekkodev/integration-test
      - name: Build sidecar
        run: |
          docker buildx build -t sidecar:current -f Dockerfile.sidecar .
      - name: Run sidecar
        run: |
          docker run --name sidecar -d -p 50051:50051 -v $GITHUB_WORKSPACE/lekkodev/integration-test:/root/lekkodev/integration-test sidecar:current --repo-path=/root/lekkodev/integration-test --mode=static
      - uses: bufbuild/buf-setup-action@v1
        with:
          buf_user: ${{ secrets.BUF_USER }}
          buf_api_token: ${{ secrets.BUF_API_TOKEN }}
          github_token: ${{ secrets.LEKKO_CI_GITHUB_PAT }}
      - name: read docker logs
        run: |
          sleep 3
          docker logs sidecar
      - name: query sidecar
        run: |
          buf curl --data '{"namespace": "default", "key": "example", "repoKey": {"ownerName": "lekkodev", "repoName": "integration-test"}}' --protocol grpc --http2-prior-knowledge --schema buf.build/lekkodev/sdk http://localhost:50051/lekko.client.v1beta1.ConfigurationService/GetBoolValue
